---
driver:
  name: vagrant

transport:
  name: winrm
  password: vagrant
  username: vagrant

platforms:
  - name: centos-7.6
  - name: tas50/windows_2019
    driver_config:
      vm_hostname: just-a-vm 
      box: tas50/windows_2019
      username: vagrant
      password: vagrant
      communicator: winrm

suites:
  - name: jtv  # just_the_vm
    driver: 
      vm_hostname: just-a-vm
  - name: mvpg # minimum viable postgres
    run_list: 
      - recipe[yes_chef::default]
      - recipe[yes_chef::backup]
    excludes:
      - tas50/windows_2019
  - name: ms
    driver:
      customize:
        memory: 3072
    run_list: 
      - recipe[yes_chef::mssql]
    excludes:
      - tas50/windows_2019
