---
driver:
  name: vagrant

platforms:
  - name: centos-7.6

suites:
  - name: jtv  # just_the_vm
  - name: mvpg # minimum viable postgres
    run_list: 
      - recipe[yes_chef::default]
      - recipe[yes_chef::backup]
  - name: ms
    driver:
      customize:
        memory: 3072
    run_list: 
      - recipe[yes_chef::mssql]
