---
driver:
  name: vagrant

platforms:
  - name: centos-7.6
    run_list: 
      - recipe[yes_chef::default]

suites:
  - name: jtv  # just_the_vm
  - name: mvpg # minimum viable postgres
    run_list: 
      - recipe[yes_chef::postgres]
      - recipe[yes_chef::backup]
      - recipe[yes_chef::debug]
  - name: trg
    run_list: 
      - recipe[yes_chef::postgres]
      - recipe[yes_chef::debug]
  - name: elk
    run_list:
      - recipe[yes_chef::elasticsearch]
